apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasure-mariaalejandramoya
  namespace: treasure-hunt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treasure-mariaalejandramoya
  template:
    metadata:
      labels:
        app: treasure-mariaalejandramoya
    spec:
      containers:
        - name: web
          image: alejandramoya/treasure-new
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "Treasure Hunt — Alejandra"
            - name: STUDENT
              value: "Maria Alejandra Moya"
            - name: SALT
              value: "DS3univalle"
            - name: KEY_HASH
              value: "2a8e4c73257b1702e36241ed8a26a5a2029c2545124c88d1af91b5e56208cd1a"
            - name: CLUE
              valueFrom:
                secretKeyRef:
                  name: mariaalejandramoya-clue
                  key: CLUE
---
apiVersion: v1
kind: Service
metadata:
  name: treasure-mariaalejandramoya
  namespace: treasure-hunt
spec:
  selector:
    app: treasure-mariaalejandramoya
  ports:
    - name: http
      port: 80
      targetPort: 80
      # nodePort: 31080   # (opcional) fija uno en el rango 30000–32767
  type: NodePort

